"""empty message

Revision ID: 1f983361c61c
Revises: e365ceab02ca
Create Date: 2024-12-12 17:53:09.349980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f983361c61c'
down_revision = 'e365ceab02ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('who_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_recoveries', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cumulative_recoveries', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('who_data', schema=None) as batch_op:
        batch_op.drop_column('cumulative_recoveries')
        batch_op.drop_column('new_recoveries')

    # ### end Alembic commands ###
