"""empty message

Revision ID: 51affe29fbc6
Revises: 1f983361c61c
Create Date: 2024-12-16 16:17:54.862002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51affe29fbc6'
down_revision = '1f983361c61c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('who_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_who_data_date_reported'), ['date_reported'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('who_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_who_data_date_reported'))

    # ### end Alembic commands ###
