"""empty message

Revision ID: aae9a5069b17
Revises: da9885b0a541
Create Date: 2024-12-10 11:41:46.834729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aae9a5069b17'
down_revision = 'da9885b0a541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('who_data', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('who_data', schema=None) as batch_op:
        batch_op.alter_column('country_code',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=True)

    # ### end Alembic commands ###
