"""empty message

Revision ID: b4bc76ecc1fd
Revises: 
Create Date: 2024-12-17 16:50:25.374339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4bc76ecc1fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_translation',
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country_korean', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    op.create_table('who_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_reported', sa.Date(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('who_region', sa.String(length=50), nullable=True),
    sa.Column('new_cases', sa.Integer(), nullable=True),
    sa.Column('cumulative_cases', sa.Integer(), nullable=True),
    sa.Column('new_recoveries', sa.Integer(), nullable=True),
    sa.Column('cumulative_recoveries', sa.Integer(), nullable=True),
    sa.Column('new_deaths', sa.Integer(), nullable=True),
    sa.Column('cumulative_deaths', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('who_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_who_data_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_who_data_date_reported'), ['date_reported'], unique=False)

    op.create_table('world_lat_long',
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('country_lat', sa.Float(), nullable=False),
    sa.Column('country_long', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_lat_long')
    with op.batch_alter_table('who_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_who_data_date_reported'))
        batch_op.drop_index(batch_op.f('ix_who_data_country_code'))

    op.drop_table('who_data')
    op.drop_table('country_translation')
    # ### end Alembic commands ###
