"""empty message

Revision ID: da9885b0a541
Revises: 
Create Date: 2024-12-10 11:39:05.636731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9885b0a541'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('who_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_reported', sa.Date(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('who_region', sa.String(length=50), nullable=True),
    sa.Column('new_cases', sa.Integer(), nullable=True),
    sa.Column('cumulative_cases', sa.Integer(), nullable=True),
    sa.Column('new_deaths', sa.Integer(), nullable=True),
    sa.Column('cumulative_deaths', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('who_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_who_data_country_code'), ['country_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('who_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_who_data_country_code'))

    op.drop_table('who_data')
    # ### end Alembic commands ###
