"""empty message

Revision ID: e365ceab02ca
Revises: 6f53c23c72cd
Create Date: 2024-12-11 16:01:45.896658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e365ceab02ca'
down_revision = '6f53c23c72cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_lat_long',
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('country_lat', sa.Float(), nullable=False),
    sa.Column('country_long', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('country_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_lat_long')
    # ### end Alembic commands ###
